### ISSUE TITLE
Mouse scrolling gets "stuck"

### ISSUE THREAD

**Issue by WhyNotHugo** [simrat39/symbols-outline.nvim#3] opened 2021-04-24 12:23 UTC
I sometimes use my mouse when scrolling a lot and I noticed that sometimes scrolling gets "stuck".

Steps to repro:

1. Open a file with lots of definitions.
2. 2. Select an entry and hit enter.
3. 3. Focus the symbols pane again.
4. 4. Try to mouse-scroll.

Scrolling only works up to the point where the entry from step 2 is at the edge of the screen. Past that, scrolling bounces right back.

Video: https://share.whynothugo.nl/f6313ece-59d3-4fbc-b184-6691e25ad70d/recording.mp4

**Comment by simrat39** [comment] 2021-04-24 21:17
@WhyNotHugo This happens because your cursor is still in the code window, so it tries to keep the currently hovered symbol in focus.
You can either:
- Disable highlight_hovered_item while setting up the plugin
- Click / Focus the symbols pane so your cursor is in it and it doesn't try to hover the symbol

I'll see if I can figure something else in the meantime

**Comment by simrat39** [comment] 2021-04-24 21:38
Looks like scrolling fires the CursorHold event which is used as a trigger for the plugin to update, and the cursor being in the code file makes it focus on that symbol again and again

**Comment by simrat39** [comment] 2021-04-25 02:20
Closing because can't really do anything because this is expected behavior, either put your cursor on the outline window or set  highlight_hovered_item to false

**Closed by simrat39** 2021-04-25 02:20 UTC
